FROM python:3.6

RUN apt-get update -yqq \
    && apt-get install -yqq --no-install-recommends \
    netcat \
    && apt-get -q clean

RUN mkdir /app
WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt
ENV FLASK_APP=app.main:app
COPY entrypoint.sh .

CMD ["./entrypoint.sh"]