FROM node:9-alpine as build-stage

RUN mkdir /app
WORKDIR /app
COPY package*.json /app/

RUN npm install
COPY . /app/
RUN npm run build

FROM nginx:alpine as production-stage
COPY --from=build-stage /app/dist/ /usr/share/nginx/html/dist
COPY --from=build-stage /app/index.html /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
